### ISSUE TITLE
BUG - WARNING binary checksum discrepancy

### ISSUE THREAD

**Issue by c-nv-s** [nsrCodes/cdd#3]
Please can you share exactly which code branch you used to build your "working example" binary, because the checksum of the built main.go code does not match your working example binary?

```
# cd ./cdd/gcdd
# go build
# sha256sum ./gcdd
604e615163d1f0b7c4b2af287caec16093ee1d2d0d73418eb8e76bef30726324  ./gcdd
# sha256sum ../../cdd/dist/bin/gcdd
2bd06b2f29699787c9f2f60e5dc3616faf7ad1bf07251cdf6aac69bb6958f55e  ../../cdd/dist/bin/gcdd
```

**Comment by nsrCodes** [comment]
Thank you for taking interest in my small project. It was made from the source file but after pushing the binary to github, I made another [commit to remove unwanted comments](https://github.com/nsrCodes/cdd/commit/64ac32ecb2a2cfd280af8a456a740f8f78587f27), I guess that is why the checksums are different.

Nonetheless, the updated binary has now been pushed.

Thank you for bringing this to my attention.
